version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: aws-0-us-west-1.pooler.supabase.com
      DB_PORT: 6543
      DB_NAME: postgres
      DB_USER: postgres.xrstrludepuahpovxpzb
      DB_PASSWORD: AZ1d3Tab7my1TubG
    ports:
      - "8000:8000"
